name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Source/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Source/**' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore ./Source/DomainServices.sln -s https://api.nuget.org/v3/index.json 
    - name: Build
      run: dotnet build ./Source/DomainServices.sln --no-restore
    - name: Test
      run: dotnet test ./Source/DomainServices.Test/DomainServices.Test.csproj --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
    - name: Publish coverage report to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./Source/DomainServices.Test/TestResults/coverage.info
